language: php
notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#webdevlabs"
    on_success: change
    on_failure: always
php:
  - '5.6'
  - '7.0'
  - '7.1'
env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"
before_script: 
  - composer self-update
  - composer update
script: phpunit Test.php
